### ISSUE TITLE
FATAL ERROR: reference '' is recognized as '*'.

### ISSUE THREAD

**Issue by jnarayan81** [barricklab/breseq#102] opened 2016-10-09 19:47 UTC
Dear There, 
I got the following error while running breseq on biolinux. Can you please assist me to resolve this?

[samtools] import ./data/reference.fasta.fai ./03_candidate_junctions/best.sam ./03_candidate_junctions/best.unsorted.bam
[sam_read1] reference '' is recognized as '*'.
[main_samview] truncated file.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error code returned by call to command: 1
FILE: samtools_commands.cpp   LINE: 97
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment] 2016-10-10 02:25
Which version of _breseq_ is packaged with biolinux? (Check the header of the run.) If it isn't the newest version (0.28.1), please try to download that version and see if the error persists.

**Comment by jnarayan81** [comment] 2016-10-12 15:32
We are using the latest version of the breseq pipeline (0.28.1). We encounter this error using the option --aligned-sam, when trying to input a sam file instead of fastq file. 
The sam file itself seems fine, as we are able to process it with samtools independently of breseq.

**Comment by jeffreybarrick** [comment] 2016-10-12 15:40
If you email me at the address in the breseq header, I can arrange a place for you to upload the problem files so that I can investigate further. Thanks.

**Comment by russianconcussion** [comment] 2016-11-01 09:33
I am having the same exact problem with the --aligned-sam option in breseq 0.28.1

**Comment by jeffreybarrick** [comment] 2016-11-01 13:33
Thanks for the additional report. This problem seems to be resolved by updating the samtools version that breseq uses internally to 1.3.1, but there appear to be some other problems introduced by this change that I haven't sorted out yet. Still working on it.

**Comment by russianconcussion** [comment] 2016-11-01 15:10
Thanks, Jeff. Yeah, I'm not sure which version of samtools that breseq is
using now, but there were some pretty big changes between 1.2 and 1.3. It
might take quite a while to sort all that out.

**Comment by jeffreybarrick** [comment] 2016-11-07 14:46
I've posted a candidate version of breseq (0.28.2rc1) in which I believe I've fixed the samtools issues. If you could test it, that would be great.

http://barricklab.org/release/breseq/

**Comment by russianconcussion** [comment] 2016-11-07 23:31
Just tested it on same data with the same command and got an error further along:
[breseq.sh.e90121-11.txt](https://github.com/barricklab/breseq/files/576913/breseq.sh.e90121-11.txt)

**Comment by jeffreybarrick** [comment] 2016-11-08 02:42
it looks like you had some partial output in that folder that could cause problems if it was from the previous version:
`--- ALREADY COMPLETE Read and reference sequence file input`
Can you try running it from a fresh (empty) output directory?

**Comment by russianconcussion** [comment] 2016-11-08 11:40
Thanks for that catch, Jeff.  I removed previous folders and reran w/same command and same input sam files.  A new error, generating an 11Gb error file, as each read wasn't mapped:
`[W::sam_parse1] urecognized reference name; treated as unmapped`

The sam file was generated by bbmap set to specific percent read match threshold, hence need to feed sam to breseq.  Trying to evaluate the biological meaning of mapping reads at different thresholds.  Also attached is a sample of sam file.  There is a special field from bbmap at the end of each row: YI: pid of read matching reference

[sorted_sam_from_bbmap.txt](https://github.com/barricklab/breseq/files/578017/sorted_sam_from_bbmap.txt)

The first 100,000 lines from error file (11Gb too large to move around).

[breseq.sh.e90163-11.head.txt](https://github.com/barricklab/breseq/files/578023/breseq.sh.e90163-11.head.txt)

The last 100 lines from error file.

[breseq.sh.e90163-11.tail.txt](https://github.com/barricklab/breseq/files/578015/breseq.sh.e90163-11.tail.txt)

**Comment by russianconcussion** [comment] 2016-11-08 11:54
Removed previous output folders and reran under same conditions.  Here is the command I ran:
`breseq --aligned-sam CP011456-7_wa25_0.95.sam -r genomes/CP011456-7.gb -j 28 -p -o CP011456-7_wa25_0.95`

The error I saw for each read was:
`[W::sam_parse1] urecognized reference name; treated as unmapped`

From which field does breseq get the reference name from the genbank file?  The name on the fasta which I used to map against may be different from the name that Breseq is getting from the reference genbank file.

Here are the beginning 100,000 and last 100 lines of the 11Gb error file generated:

**Comment by russianconcussion** [comment] 2016-11-08 14:09
Okay, I've done some troubleshooting with my input files and now I've gotten to the point where breseq is telling me that there are more mismatches than matches in my read alignment.  I'm not sure how that's possible, since I set the read identity threshold to 95% when preparing the sam file with bbmap ...

`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
More mismatches than matches for read alignment. 
FILE: candidate_junctions.cpp   LINE: 102
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

Error file:

[breseq.sh.e90219-11.txt](https://github.com/barricklab/breseq/files/578337/breseq.sh.e90219-11.txt)

**Comment by aderzelle** [comment] 2016-11-08 16:21
Hello, 
I am a colleague of the original poster, we are trying the new  0.28.2rc1 with a sam file but we now have the following error 
[error_breseq.txt](https://github.com/barricklab/breseq/files/578719/error_breseq.txt)

**Comment by jeffreybarrick** [comment] 2016-11-08 16:34
aderzelle, I think this might be a problem related to R running on your system (and possibly a disk space or RAM usage issue). Try rerunning just the command that had a problem (below). If it works, then the problem is outside of breseq, or possibly a transient resource usage issue on your machine and re-running the brese command to continue processing may work.

`R --vanilla < /media/urbe/MyADrive/breseq_test/breseq-0.28.2rc1-Linux-x86_64/bin/../share/breseq//coverage_distribution.r > ./07_error_calibration/10156.unique_only_coverage_distribution.tab.r.log distribution_file=./07_error_calibration/10156.unique_only_coverage_distribution.tab plot_file=./output/calibration/10156.unique_coverage.pdf deletion_propagation_pr_cutoff=0.00187912`

As a follow-up question: how many contigs do you have in your reference genome? I see some of these bugs are being reported when using >20,000 contigs and genomes >200 MB, which is a type of reference that breseq wasn't really intended for. I'm happy to try to make breseq robust to this scale of data, but I may need some example data sets to test from you. If you'd be willing to provide one (perhaps this one that has the problem), please contact me by email (at the address in the breseq header), and I will give you access to a shared folder to upload it.

Thanks for your patience!

**Comment by jeffreybarrick** [comment] 2016-11-09 17:00
For the `More mismatches than matches for read alignment. FILE: candidate_junctions.cpp LINE: 102` error, I'm not real sure what is going on. It would be helpful to me to see your SAM file. If you email me at the address in the _breseq_ header I can give you access to a shared folder to upload the test data and debug.

**Comment by jeffreybarrick** [comment] 2016-12-14 03:02
Issues related to SAM input have been fixed in the repo code and will be in the v0.29.0 release. If there are remaining problems, please open a new issue.

**Closed by jeffreybarrick** 2016-12-14 03:02 UTC
