### ISSUE TITLE
'std::out_of_range' at the 'Predicting mutations from evidence...' (08) step of breseq analysis

### ISSUE THREAD

**Issue by jmath97** [barricklab/breseq#248] opened 2020-10-04 20:59 UTC
Hi,

I'm working with a deep sequencing data set that covers the whole genome of S. aureus. I have been using the breseq pipeline and it has been helpful for most of my data sets; however, for this particular sample, I keep running into errors.

When I initially set up the analysis, the first error I received was an error at the sequence conversion step (01); there was an error at ~100,000,000 reads into a ~150,000,000 read file. The program suggested to use the 'head' function to clip the file at the site of the error and use that new file as an input into the breseq pipeline. When I ran this new analysis (with the modified fastq file), I received a 'std::out_of_range' error when it was trying to 'predict mutations from evidence'.

Do you have any suggestions for how I can fix this error?

I'm running these samples on a Linux-RedHat HPC cluster. The versions of breseq, bowtie2, and R are 0.35.3, 2.4.1, and 3.6.1, respectively.

If you need the output files, I'd be more than happy to provide them. Thank you for your help and input!

**Comment by jeffreybarrick** [comment] 2020-10-04 21:03
Hi,

If you can share the input files and command to help me reproduce the error, please send me an email at the address in the _breseq_ header, and I can share a location where you can upload them.

**Comment by jeffreybarrick** [comment] 2020-12-06 19:53
Were you able to resolve this?

I'm not sure what the problem might be. I was able to run your files without either error on MacOSX with _breseq_ 0.35.4, bowtie2 2.3.4.1, and R 4.0.0.

The input FASTQ files are quite large, so I wonder if you might be getting an error due to a disk write problem or using up disk space.

Only 4.4% of the reads overall map. There appear to be adaptors left on the ends of many, which might be why this is happening. (Since _breseq_ requires 90% of the length of the read to align by default, if more is adapter, then it will not align them.) Also, the reads seem to map in a blocky fashion that may indicate a low complexity DNA input into library prep (see picture).
 
![Screen Shot 2020-12-06 at 1 40 21 PM](https://user-images.githubusercontent.com/6777876/101290829-35c5a980-37ca-11eb-80e0-33e942ec4fa3.png)

**Comment by jeffreybarrick** [comment] 2020-12-06 21:05
Ah right, nevermind! I remember now that these are SSC reads... I see your commands file now and will try to follow that procedure and see if it works.

**Comment by jeffreybarrick** [comment] 2020-12-08 18:07
I was also able to get the SSC reads to work fine, so I'm going to close this and assume that it was related to some corruption of the files, perhaps related to the output you got from the `SSCS_DCS.py` script. Let me know if you have any other ideas.

**Closed by jeffreybarrick** 2020-12-08 18:07 UTC

**Comment by jmath97** [comment] 2020-12-08 18:26
Hi Prof. Barrick,

I was actually able to get the pipeline to work out. I was able to get this
to work out a few weeks ago actually so I apologize for not responding
sooner! My understanding of the file re-formatting that occurs was a bit
obscured and after I figured that out, I was able to fix up the rest of the
analysis.

So sorry for the lack of notice. Thank you SO much for all of your help.

Best,
Jacob
