### ISSUE TITLE
Update/maintain/support Galaxy wrapper for breseq

### ISSUE THREAD

**Issue by jeffreybarrick** [barricklab/breseq#209] opened 2019-09-20 15:11 UTC
Version maintained by Daniel Sobral is here:
https://testtoolshed.g2.bx.psu.edu/repository?repository_id=0afaeabc020e2004

Steps:
- [ ] Set up Galaxy instance and test current version on AWS
- [ ] Update to use latest breseq version
- [ ] Get others to test
- [ ] Make more _breseq_ options and/or output files visible to the Galaxy interface

**Comment by hepcat72** [comment] 2019-09-23 17:29
Hi.  Is this being actively worked on?  We had a request to add breseq and one of its associated utilities to our galaxy installation, but I wouldn't want to duplicate efforts already underway...

**Comment by jeffreybarrick** [comment] 2019-09-23 17:42
This thread was to start planning to kick off an effort and recruit someone to work on this b/c we have had a request to use _breseq_ in this way in an educational setting. We do not have any Galaxy experience or a server set up for development, so it would take us some time to get up and running. We would gladly hand it off to you and/or coordinate with you if you have more experience.

My understanding is that the version from Daniel Sobral posted above worked for several years but is no longer maintained and needs to be updated/extended, so that would probably make a good starting point.

**Comment by hepcat72** [comment] 2019-09-23 17:55
Glad I asked.  I've done a few galaxy wrappers - not very many TBH, but some.  Before we saw this post, we were planning on implementing the bare minimum parameters that our user said they would use, although having the previous wrapper is a good start.

Perhaps we could implement to suit our needs (keeping anything that's not broken) and if your user wants more, we can evaluate from there?  Can't make any promises as to time, but we definitely need to get it done one way or another.  Our user has checked in once recently and we haven't had the time yet to devote to it.

Incidentally, you don't actually need to set up a dev server for one tool wrapper.  Planemo will run one for you on your desktop on the fly.

**Comment by hepcat72** [comment] 2019-10-16 16:34
Incidentally, I have started working on this.

**Comment by jeffreybarrick** [comment] 2019-10-16 17:04
Great to hear. Let us know if you run into any problems that could be solved on the _breseq_ side. I believe there is a compatibility issue with the existing code where you have to either turn off javascript generation in the _breseq_ HTML output (use `--no-javascript` flag) or set an option to allow javascript on the Galaxy server settings.

Thanks for pointing out the Planemo tool.

**Comment by hepcat72** [comment] 2019-10-16 17:09
I ran into an issue with everything outside of the body tags already, but white-listing the tool fixes that.  That may address the javascript issue.  Unfortunately, that has to be done by the galaxy admin of each galaxy instance that installs the tool.

Just so I can confirm functionality, what operations are done by javascript that I can check.  I mean, I could look at the code, but...

**Comment by hepcat72** [comment] 2019-10-16 17:35
So far, I’ve tested with the basic lambda dataset. I didn’t find a deletion in my quick search. Which data has the deletions?

**Comment by jeffreybarrick** [comment] 2019-10-16 17:45
The test `REL606_fragment_deletion_between_is` has a nice quick example.

The command line to run is:
`breseq -o <output> REL606.fragment.gbk REL606.fragment.2.fastq`

The data files are under: `tests/data/REL606`

![Screen Shot 2019-10-16 at 12 42 27 PM](https://user-images.githubusercontent.com/6777876/66944256-7389d080-f012-11e9-9f7f-b6d2cef18274.png)

**Comment by hepcat72** [comment] 2019-10-16 19:57
The javascript appears to work once the tool is whitelisted.

**Comment by hepcat72** [comment] 2019-10-16 20:09
I've got to get some stuff done on another project, so I'm done with this for today.  I've got the commonly used parameters done.  Here's a sample of it in action.  Note, I forgot to whitelist the tool before doing the screen recording.  I whitelist it during the recording, but it's offscreen.  Comments?

https://www.dropbox.com/s/yflrg4ph3rnb2lt/breseq_small.mov?dl=0

**Comment by hepcat72** [comment] 2019-10-17 21:43
Got a simple/small test working today while working on another project.  We decided to just implement the commonly used options.  I'll likely move on to a wrapper for gdtools next.

**Comment by jeffreybarrick** [comment] 2019-10-21 03:08
This looks great. Let me know when you have it at a point where you want others to try it out.

**Comment by hepcat72** [comment] 2019-10-21 18:08
How should I test `gdtools annotate`? Do you have a small example with expected output?

**Comment by hepcat72** [comment] 2019-10-21 18:37
Incidentally, it looks like this page is based on an old version (since there is no `--html` flag):

http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/gd_usage.html

**Comment by hepcat72** [comment] 2019-10-21 21:21
I submitted a PR

https://github.com/galaxyproject/tools-iuc/pull/2655

You can clone my repo if you'd like to test:

https://github.com/hepcat72/tools-iuc/

**Comment by hepcat72** [comment] 2019-10-21 21:23
To test, you can:

```
cd tools-iuc/tools/breseq
planemo serve
```

**Comment by hepcat72** [comment] 2019-10-24 22:18
The breseq galaxy wrapper is going into its second round of reviews in the IUC tools repo.  I thought I would share it with you in case you had any feedback.

https://github.com/galaxyproject/tools-iuc/pull/2655

**Comment by jeffreybarrick** [comment] 2019-10-25 13:13
I was able to run a larger test through planemo just fine. It looks great!

One main suggestion would be to set it up so that _breseq_ can use multiple threads to speed up runs. You can pass the `-j` argument for this. 

I also wonder if it is also possible to view/update the terminal output somehow through Galaxy so that a user could see how the run is progressing for a long job.

**Comment by hepcat72** [comment] 2019-10-25 13:31
The -J option is used, but it can only be configured by an admin and unfortunately galaxy doesn’t have the ability to show live output. It would be great if it did.

**Comment by hepcat72** [comment] 2019-10-28 19:28
Incidentally, -j is maintained dynamically per job.  `planemo` sets it to 1 and is only intended to be used for small tests on a single-core/small machine.  On a cluster, admins set it for all tools based on cluster topology.  The default value I set for the tool was 4 (but that default is only used if the admin hasn't specified something in the config for the machines and queues/partitions it will run on).

I just issued some updates to the wrapper, but they're all technical/behind-the-scenes changes.  The interface is still the same.  I'm hoping this will be the last round of reviews and that it will get merged this week.  I'm not sure exactly when it might get pushed out to the toolshed.

**Comment by hepcat72** [comment] 2019-10-30 21:05
It has been merged into the IUC.  It should show up in the main toolshed at some point in the near future.

Note, I had to change the interface a bit.  yesterday, the reviewers complained that the reference inputs used "galaxy internals", which they discourage.  I had to change it to a repeat with a single-item select list for builtin references, but I realized that doing it that way would allow you to use a reference from your history with a builtin reference, which I couldn't do the way I'd initially set it up.  Still, it would have been nice to have a multiple item select list.  It's just not supported for builtin references apparently.  Anyway, it works and is out there!

You can close this issue.

**Comment by jeffreybarrick** [comment] 2019-10-31 01:53
This is fantastic. Thanks so much for your work on it!

How do you want to coordinate maintaining the _breseq_ wrapper? Should we feel free to make further updates directly to IUC to update for future tool versions or would you prefer that we run this through/by you?

**Comment by hepcat72** [comment] 2019-10-31 04:13
I’m fine with whatever. If you would like to add options, please feel free. Just fork the tools-iuc repo, make your changes, then submit as a pull request. If you tag me in the PR, I’ll have a look.

**Closed** 2019-10-31 10:35 UTC
Labels: coding-project
