### ISSUE TITLE
Breseq v0.30.0 with Bowtie2 v2.3.1

### ISSUE THREAD

**Issue by pkelly589** [barricklab/breseq#116] opened 2017-04-04 23:16 UTC
When using the newest version of Bowtie2, Breseq often crashes with the error:

> Creating merged genome diff evidence file...
> Predicting mutations from evidence...
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  basic_string::substr: __pos (which is 18446744073701026151) > this->size() (which is 9001671)
> Aborted (core dumped)

If the process does run to completion, no reads were actually aligned to the genome (average read coverage <5X, and the majority of genome is classified as "low coverage").

I've reverted to Bowtie2 v2.2.9 (still with Breseq v0.30.0) and it seems to have solved the problem

**Comment by jeffreybarrick** [comment] 2017-04-06 00:20
Thanks for the report. I'll check it out and contact you if I can't reproduce the problem with another data set.

**Comment by dannagifford** [comment] 2017-04-06 05:53
I have also had this issue and can confirm downgrading bowtie2 also fixed it for me.

**Comment by jeffreybarrick** [comment] 2017-04-08 17:20
This seems to be due to a bug in the new bowtie2 version (2.3.1) where it outputs a spurious non-SAM line in the SAM file output after certain types of read alignments, and this has bad consequences downstream in _breseq_. I've reported this bug, so hopefully it will be fixed in the next bowtie2 release.

The best solution for now is to use bowtie2 v2.3.0 or earlier.

**Comment by jeffreybarrick** [comment] 2017-05-10 22:04
Bug in bowtie2 is fixed in v2.3.2

**Comment by vr1087** [comment] 2017-06-09 15:45
I was getting this error while running breseq v0.28.0 with bowtie2 v2.2.9 and after upgrading both softwares to breseq v0.30.0 and bowtie2 v2.3.2, the error has persisted. Perhaps the bug fix in the new bowtie2 release does not catch all problematic read alignments? What other information/data can I provide to help?

```
=============================================================================
breseq 0.30.0  revision f53f5bf51c1f   http://barricklab.org/breseq

=============================================================================
---> bowtie2  :: version 2.3.2 [/usr/local/bin/bowtie2]
---> R        :: version 3.2.3 [/usr/bin/R]

+++   NOW PROCESSING Output
Creating merged genome diff evidence file...
Predicting mutations from evidence...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073706757312) > this->size() (which is 4364213)
134
```

**Comment by jeffreybarrick** [comment] 2017-06-09 15:51
You started running the new versions from an entirely clean output directory, correct? (No "already done" messages.) I'll probably need the input files to diagnose if that is not the problem. You can email me if you are willing to share them and I will set up a shared folder.

**Comment by vr1087** [comment] 2017-06-09 16:02
Yes, that's right. I understood that I had to start from scratch, deleting the old output directory.

**Comment by jeffreybarrick** [comment] 2017-07-12 21:53
Resolved!

**Closed by jeffreybarrick** 2017-07-12 21:53 UTC
